GENEROS_DE_LIVROS = ["História(0)", "Geografia(1)", "Romance(2)",  "Fantasia(3)",  "Poesia(4)",  "Outros(5)"]

ANOS = list(range(2000, 2025))
EDITORAS = [
    "Editora Arco-Íris",
    "Editora Girassol",
    "Editora Páginas Coloridas",
    "Editora Lua Crescente",
    "Editora Estrela Cadente",
    "Editora Livro Encantado",
    "Editora Mundo Mágico",
    "Editora Fantasia Ilimitada",
    "Editora Sussurros Noturnos",
    "Editora Sonhos Dourados",
    "Editora Aventuras Infinitas",
    "Editora Folhas ao Vento",
    "Editora Labirinto de Letras",
    "Editora Mar de Histórias",
    "Editora Mistérios e Enigmas",
    "Editora Espaço Literário",
    "Editora Viagem aos Sonhos",
    "Editora Noites Estreladas",
    "Editora Páginas de Encantar",
    "Editora Floresta de Livros"
]
NOMES_DE_LIVROS = [
    "As Aventuras de Sir Galo Doido e o Reino dos Ovos Fritos",
    "O Segredo do Abacate Azul e Outras Histórias Estranhas",
    "A Incrível Saga de Bob, o Cachorro que Virou Astronauta",
    "O Manual Completo de Como Convencer seu Gato a Pagar o Aluguel",
    "A Grande Jornada de Plínio, o Pato Aventureiro, pelo Pantanal Proibido",
    "101 Receitas de Brigadeiro para Todas as Ocasiões, Inclusive Funerais",
    "O Mistério da Meia Desaparecida e Outras Conspirações Domésticas",
    "A Fantástica Odisséia de Frank, o Mamute Hipocondríaco",
    "Piratas no Espaço: A Busca pelo Tesouro Interplanetário",
    "O Guia Definitivo para Sobreviver à Invasão dos Unicórnios Zumbis",
     "O Pato que Virou Mago e Fez Feitiços com Pães de Queijo",
    "A Revolta dos Tomates Assassinos e a Guerra da Salada",
    "O Guia Definitivo de Como Treinar seu Dragão Doméstico",
    "As Peripécias de Pedro, o Porco Detetive",
    "O Mistério do Chocolate Sumido na Fábrica de Coelhos",
    "O Inventor Maluco e o Robô que Tinha Medo do Escuro",
    "A Incrível História de João, o João-ninguém",
    "Os Estranhos Casos de Tião, o Tatu Detetive",
    "O Padeiro que Fugiu com a Lua e Voltou com Bolinhos Estelares",
    "A Fuga do Elefante que Sonhava em Ser Pianista",
    "O Dia em que o Sol se Escondeu e os Pássaros Ficaram de Plantão",
    "A Aventura de Mabel, a Minhoca Maluca, no Mundo dos Livros",
    "Os Piratas da Lagoa Encantada e o Tesouro das Bananas de Ouro",
    "O Cientista Maluco e a Fórmula Secreta da Risada Infinita",
    "O Livro Proibido dos Contos de Fadas Politicamente Incorretos",
    "O Mistério dos Chapéus Voadores na Cidade das Nuvens",
    "A Odisseia de Otávio, o Ornitorrinco Filósofo",
    "Os Super-Heróis Desastrados e o Plano para Salvar o Dia",
    "A Rebelião das Cenouras e a Revolta dos Brócolis",
    "O Conde que Queria ser Cantor de Rock e Outras Histórias Bizarras"
]